version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_reservasuno
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: reservasuno
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
